#!/bin/bash
# Build FSST-compressed twins of the benchmark databases that only exist
# uncompressed, so regex_report.py can run its suites with --fsst.
#
# WHY COPY RATHER THAN REGENERATE
# -------------------------------
# regex_gen.py can rebuild the `patterns` tables at a chosen encoding, but the
# sel_/par_/threads tables are not generated by anything still in the repo. Even
# where a generator exists, regenerating reseeds the data: the twin would hold
# DIFFERENT strings, and its numbers could not be compared against the recorded
# uncompressed results. So this copies the rows verbatim -- same rows, same order,
# same row count, therefore the same row-group geometry, which is itself an
# experimental variable (see CLAUDE.md: 32 x 122880 is load-bearing).
#
# IT MUST BE THE LOCALLY BUILT duckdb
# -----------------------------------
# This fork encodes FSST with zeroTerminated=1 (code 0 reserved as terminator),
# which is what makes the NUL-framed wire format work. A stock duckdb writes
# mode-0 tables that the passthrough cannot use, and nothing would report the
# difference -- the tables would just look like ordinary FSST storage.
#
# WHAT CANNOT BE TWINNED
#   * ASEL_DB (asel_0..asel_100, the anchored half of the selectivity suite) does
#     not exist in ANY encoding, and no generator for it survives in the repo --
#     only results/selectivity_anchored.csv. That suite half is already unrunnable;
#     a compressed-only version would not restore comparability either.
#   * Strings >= 4096 B are stored Uncompressed by DuckDB whatever
#     force_compression says (measured: a 4096 B column comes back Uncompressed).
#     So par_4096 stays uncompressed and par_2048 is borderline. That is a storage
#     limit, not a failure here -- the script reports each table's real encoding.
#
# USAGE
#   scripts/regex_gen_fsst_twins.sh              # all three, into /local/home/vifranz
#   ONLY=sel scripts/regex_gen_fsst_twins.sh     # one of: sel par threads
#   DST_DIR=/scratch/vifranz scripts/...         # put them on NFS instead
# Idempotent: a table that already exists in the twin is left alone.
set -u

D=${DUCKDB:-/home/vifranz/oasis/extension/build/release/duckdb}
# Sources are the recorded uncompressed set on NFS; the twins go to LOCAL disk.
# /scratch is NFSv4 sec=krb5p at ~39 MB/s, and regex_report.py already expects to be
# pointed at a local copy (see its REGEX_DB_DIR note), so writing the twins to /local
# both builds them faster and puts them where a run should read them from.
SRC_DIR=${SRC_DIR:-/scratch/vifranz}
DST_DIR=${DST_DIR:-/local/home/vifranz}
# NFS at ~39 MB/s makes it a terrible place to spill. /local is a real disk.
TMPDIR_DUCKDB=${TMPDIR_DUCKDB:-/local/home/vifranz/duckdb_tmp}
THREADS=${THREADS:-16}
ONLY=${ONLY:-}

export LD_LIBRARY_PATH=$HOME/opt/lib:${LD_LIBRARY_PATH:-}
mkdir -p "$TMPDIR_DUCKDB"

die() { echo "FATAL: $*" >&2; exit 2; }
[ -x "$D" ] || die "no duckdb at $D (must be the local fork: mode-1 FSST)"
mkdir -p "$DST_DIR" || die "cannot create $DST_DIR"
# The twins are ~1/3 of 45 GB of sources, plus spill. Fail early, not mid-copy.
avail=$(df -BG --output=avail "$DST_DIR" | tail -1 | tr -dc 0-9)
[ "${avail:-0}" -ge 30 ] || die "only ${avail}G free on $DST_DIR; need ~30G"

twin() {  # $1 = basename without _uncompressed
    local src="$SRC_DIR/${1}_uncompressed.duckdb"
    local dst="$DST_DIR/${1}_fsst.duckdb"
    [ -r "$src" ] || { echo "SKIP $1: no $src"; return 0; }
    echo "=== $1"
    echo "    src $src ($(du -h "$src" | cut -f1))"
    echo "    dst $dst"

    local tables
    tables=$("$D" -readonly "$src" -noheader -list \
             -c "SELECT table_name FROM duckdb_tables() ORDER BY 1;") || die "cannot list $src"

    for t in $tables; do
        # Idempotent: skip a table the twin already has.
        if [ -f "$dst" ] && "$D" -readonly "$dst" -noheader -list \
             -c "SELECT 1 FROM duckdb_tables() WHERE table_name='$t';" 2>/dev/null | grep -q 1; then
            echo "    $t: already present, skipping"
            continue
        fi
        echo -n "    $t: copying... "
        local s=$(date +%s)
        "$D" "$dst" -noheader -list -c "
            SET threads=$THREADS;
            SET temp_directory='$TMPDIR_DUCKDB';
            SET preserve_insertion_order=true;
            SET force_compression='fsst';
            ATTACH '$src' AS src (READ_ONLY);
            CREATE TABLE \"$t\" AS SELECT * FROM src.\"$t\";
            DETACH src;
            CHECKPOINT;
        " >/dev/null 2>"$TMPDIR_DUCKDB/$1_$t.err" \
            || { echo "FAILED"; sed 's/^/        /' "$TMPDIR_DUCKDB/$1_$t.err" | head -5; continue; }
        echo "$(( $(date +%s) - s ))s"
    done

    # Report what the storage layer actually chose, per table. Never assume FSST:
    # force_compression is a request, and long strings override it.
    echo "    --- verification ---"
    # pragma_storage_info only accepts a LITERAL table name -- it cannot be joined
    # against duckdb_tables(), so verify one table per query. Report the encoding the
    # storage layer actually chose: force_compression is a request, and DuckDB stores
    # strings >= 4096 B Uncompressed regardless of it.
    for t in $tables; do
        local enc rows srows
        enc=$("$D" -readonly "$dst" -noheader -list \
              -c "SELECT string_agg(DISTINCT compression, ',') FROM pragma_storage_info('$t')
                  WHERE compression <> 'Constant';" 2>/dev/null)
        rows=$("$D" -readonly "$dst" -noheader -list -c "SELECT count(*) FROM \"$t\";" 2>/dev/null)
        srows=$("$D" -readonly "$src" -noheader -list -c "SELECT count(*) FROM \"$t\";" 2>/dev/null)
        if [ "$rows" = "$srows" ]; then match="rows=$rows ok"; else match="ROW COUNT MISMATCH src=$srows dst=$rows"; fi
        case "$enc" in
            *FSST*) verdict="FSST" ;;
            *)      verdict="NO FSST (passthrough cannot fire)" ;;
        esac
        echo "    $t: enc=$enc $match -> $verdict"
    done
    echo "    size $(du -h "$dst" | cut -f1)"
}

for name in regex_sel_rg128 regex_par32 regex_threads480; do
    case "$ONLY" in
        "")      ;;
        sel)     [ "$name" = regex_sel_rg128   ] || continue ;;
        par)     [ "$name" = regex_par32       ] || continue ;;
        threads) [ "$name" = regex_threads480  ] || continue ;;
        *) die "ONLY must be sel, par or threads" ;;
    esac
    twin "$name"
done
echo "done."
